### PR TITLE
Keeping last stack value in local variable ~20% slower

### PR DESCRIPTION
**Pull request by jpastuszek**
Looks cleaner and avoids need to have two scopes; also keeping action on the frontier.
Somehow slower though :/

### CODE REVIEW

**Comment by jpastuszek** [comment]
Some cleanups to make it easier to compare with your PR.
This is 25% slower than your PR... I wonder if this is because I mix stack (remaining_actions) and heap access (frontier). CPU cache misses? Any ideas?

**Comment by jpastuszek** [comment]
I like this code better because here I avoid having to use Option type in frontier and therefore need for filter_map and Action: Clone bound... but not for the speed cost! :/
If we can't fix speed problem we should merge your PR.

**Comment by aldanor** [comment]
Yea, maybe my version is more cache friendly? Idk, if you refactor it even further so it has similar variable names and all so it's easier to compare we could ask on Rust IRC. 

Do you think Clone bound can actually be removed in my version?

**Comment by jpastuszek** [comment]
Yes, try stack.into_iter() and you should get away with cloned().

**Comment by jpastuszek** [comment]
without*

**Comment by aldanor** [comment]
I'm not at the computer right now so can't check but I think that didn't work... if you can make it work could you open a PR to my PR? :)

**Comment by jpastuszek** [comment]
I run valgrind (callgrind and cachegrind) on both versions:

https://gist.github.com/jpastuszek/9a28a1fbcf8f21235c5d
https://gist.github.com/jpastuszek/db14e6639bd477aeb5c1

The only think I can tell is that in your versions pop() takes 20% less time than push() while in my version it takes the same. 
I think the reason for this is that in you case you don't copy actions (iterator) - you take it by reference on top of the loop - while I copy it out with pop to stack and than use by value on top of the loop (.next()).

**Comment by aldanor** [comment]
Wow that's some good research! I never tried running valgrind on Rust stuff, so you can actually annotate it line by line? Care to share how exactly?

**Comment by aldanor** [comment]
I think I figured it out (`valgrind` / `callgrind_annotate`), I wonder though why some lines are not annotated, like the one where the hash is checked (if you uncomment it).

**Pull request closed without merging**
